### ISSUE TITLE
run-war does not work

### ISSUE THREAD

**Issue by harbdog** [kensiprell/grails-atmosphere-meteor-sample#23]
I'm trying to see if I can implement Meteor in my project, first trying to get the sample deploying.  On my machine (windows 10 x64, grails 2.4.5, jdk1.7.0_80) I cannot get grails run-war to work on the meteor sample project, even though run-app does work on it. However, run-war does work on my own grails project (https://github.com/harbdog/roguemek). Here's the error I see immediately after issuing run-war command:

`| Done creating WAR target\grails-atmosphere-meteor-sample-1.0.5.war
| Running Grails application
|Enabling Tomcat NIO Connector
Exception fixing docBase for context [/grails-atmosphere-meteor-sample]
java.io.IOException: Unable to create the directory [C:\Users\eric\git\grails-atmosphere-meteor-sample\tomcat.8080\webapps\grails-atmosphere-meteor-sample]
        at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:115)
        at org.apache.catalina.startup.ContextConfig.fixDocBase(ContextConfig.java:618)
        at org.apache.catalina.startup.ContextConfig.beforeStart(ContextConfig.java:744)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:307)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)`

This is the only lead I have so far, but obviously doesn't help me out much since it's still unresolved. Any ideas on how to workaround the problem so I can deliver a war?
https://jira.grails.org/browse/GRAILS-11376

**Comment by kensiprell** [comment]
Check the grails user write permissions along the path (C:\Users\eric\git\grails-atmosphere-meteor-sample\tomcat.8080\webapps\grails-atmosphere-meteor-sample). I think this is a common problem with Windows.

Ken

**Comment by harbdog** [comment]
My user (eric) has full permissions to these folders in its Users dir, the problem seems to be that the actual folders being created differ in path location from what it is expecting.

The exception states that it is looking for:
C:\Users\eric\git\grails-atmosphere-meteor-sample\**tomcat.8080\webapps\grails-atmosphere-meteor-sample**

But when I browse the directory what I find is this was created by the run-war process:
C:\Users\eric\git\grails-atmosphere-meteor-sample\**tomcat.8080\work\Tomcat\localhost\grails-atmosphere-meteor-sample**

**Comment by kensiprell** [comment]
I was using my phone on my first comment, and I overlooked the part about run-war working with your other app. I thought it could be a problem with whatever user the Grails process runs under on Windows. I use OSX altough I do test releases on Windows but not run-war.

After reading your comment and the Jira link you provided, it looks like you have hit a Grails bug. I'm travelling now and don't have access to my laptop to troubleshoot, but I don't think it's an issue with the plugin or sample app.

You mentioned needig to deliver a war. Can't you build one and deploy it to a container? I never trusted the run-war option anyway for testing. I've had trouble with that in the past.

**Comment by harbdog** [comment]
Ah I didn't realize the run-war was not to be trusted, now I know! I was kind of hoping maybe there was some configuration change that could have worked but I can see its a Grails bug they haven't fixed.

Thanks though, building the war and deploying it to a separate tomcat server worked with no issues, so problem solved!
